### ISSUE TITLE
New release to fix IntelliJ 2021.2+ (#9)

### ISSUE THREAD

**Issue by recombinationgroup** [anonfunc/intellij-voicecode#10]
First of all thank you for the great plugin! It's a great help to me. The current master branch contains a fix which enables compatibility with intellij 2021.2+. I compiled the plugin locally, which works flawlessly.  even better would be an official release, to enable installation from the marketplace. Do you have any plans to release v0.0.11? thanks in advance!

**Comment by anonfunc** [comment]
Submitted to Jetbrains.
